spring:
  profiles:
    active: dev
  application:
    name: front-server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    url: redis://127.0.0.1:6379

server:
  port: 8088

security:
  basic: # 启用基本身份认证
    enabled: true
  user:
    name: makelife
    password: makelife!qaz

  oauth2:
    resource:
      id: front-server
#      filter-order: 3

# 去掉springboot-actuator 鉴权
management:
  security:
    enabled: false
