spring:
  profiles:
    active: dev
  application:
    name: front-server

server:
  port: 8088

#security:
#  basic: # 启用基本身份认证
#    enabled: false
#  user:
#    name: makelife
#    password: makelife!qaz
#
#  oauth2:
#    resource:
#      id: front-server
##      filter-order: 3
#
## 去掉springboot-actuator 鉴权
#management:
#  security:
#    enabled: false
