spring:
  profiles:
    active: dev
  application:
    name: front-server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 8088

logging:
  path: '${user.home}/logs/${spring.application.name}'

security:
#  basic:
#    enabled: true
  user:
    name: makelife
    password: makelife!qaz
