#mybatis:
#mapper-locations: classpath:mapper/*.xml #Mapper的xml文件
#type-aliases-package: com.makelife.*.domain #实体类的包
#
#mapper:
#mappers: com.makelife.backhandparent.data.TkMapper
#not-empty: false
#identity: postgresql